
#Embedded LDAP server config:
spring:
  ldap:
    embedded:
      port: 8389
      ldif: classpath:ldap/ldap-data.ldif
      base-dn: dc=springframework,dc=org
      validation:
        enabled: false
      credential:
        username: uid=admin
        password: secret